### ISSUE TITLE
Make Apache Alias Optional

### ISSUE THREAD

**Issue by smith** [coroutine/chef-kibana#2]
For the apache recipe, it defaults to /kibana for the alias, and / doesn't work for me. Make it so the alias is optional (wrapped in an if statement or something) so you can just have the document root be /.

**Comment by jdugan** [comment]
Hi, Nathan.  The alias is set via an attribute.  If you'd like it to be something other than `/kibana`, you can simply override the attribute to whatever you like.

**Comment by smith** [comment]
I understand that, but if you set the alias to "/", you get a directory listing instead of the app. I don't think mod_alias handles this and just assumes you should use DocumentRoot if you're aliasing the root. 

I'll open a pull request if I get around to it, but I'd contend that this is still a valid issue. Have you been able to just alias / and have it work? I could have something set up wrong.

**Comment by jdugan** [comment]
No, I hadn't.  I misunderstood what you were reporting.

If you have time for a patch, it would be gratefully accepted.  As I'm sure you know, almost all Chef cookbooks (and Chef itself) are works in progress at that point.

**Comment by smith** [comment]
Opened https://github.com/coroutine/chef-kibana/pull/3

**Comment by jdugan** [comment]
Accepted with thanks.
